### PR TITLE
Create Test GT

### PR DESCRIPTION
**Pull request by G-Thiara**

### CODE REVIEW

**Comment by TomBradyWannabe** [comment]
Needs more Tom Brady. Denied.

**Comment by sunmeng0421** [comment]
WTH?

**Comment by friendface1** [comment]
GT THIS IS TERRIBLE

**Comment by AmmarHub** [comment]
Pathetic...

**Comment by liiaang** [comment]
Why didn't you say anything?

**Comment by laidem** [comment]
Unclear

**Comment by PeterBell** [comment]
Feels little formulaic - thoughts @friendface1

**Comment by AmmarHub** [comment]
really GT??

**Comment by dianamcho** [comment]
More Tom Brady!

**Comment by SeanOMealia** [comment]
I really like this code and think we should add it. Awesome work @G-Thiara !!! :sake:

**Comment by G-Thiara** [comment]
*deletes Github account*

**Comment by friendface1** [comment]
@peterbell ... it's RUBBISH

**Comment by PeterBell** [comment]
How about you add something more to the file @G-Thiara

**Comment by G-Thiara** [comment]
Thanks Sean. You're my true friend.

**Comment by TomBradyWannabe** [comment]
Great change. T Brizzle would be proud. :point_up_2:

**Comment by acc483** [comment]
i hate dogs

**Comment by certify** [comment]
I think this should definitely be part of the project :+1: - lets :ship: it

**Comment by AmmarHub** [comment]
+1

**Comment by jlichtinger** [comment]
:+1 :+1 :+1 :+1 :+1 :+1 :+1

**Comment by LSouza16** [comment]
+1

**Comment by dianamcho** [comment]
:+1:

**Comment by AmmarHub** [comment]
:+1:

**Comment by vincetibone** [comment]
:8ball:

**Comment by jwvirus** [comment]
:100:

**Comment by SeanOMealia** [comment]
I liked the old version a lot better.  Stop the presses :newspaper: :-1:

**Comment by LSouza16** [comment]
:+1:

**Comment by acc483** [comment]
:+1:

**Comment by LSouza16** [comment]
:-1:

**Comment by BenKozy** [comment]
:japanese_ogre:

**Comment by certify** [comment]
colbert

**Comment by liiaang** [comment]
http://ak-hdl.buzzfed.com/static/2014-11/1/16/enhanced/webdr08/anigif_enhanced-4451-1414873673-1.gif

**Comment by friendface1** [comment]
http://giphy.com/gifs/funny-karaoke-8kUINu7qyHB8Q

**Comment by G-Thiara** [comment]
Guys, take it easy. My gmail is spammed with updates.

**Comment by certify** [comment]
newgif

**Comment by BenKozy** [comment]
clj36

**Comment by friendface1** [comment]
:[{newgif}http://giphy.com/gifs/funny-karaoke-8kUINu7qyHB8Q

**Comment by certify** [comment]
newgif

**Comment by certify** [comment]
ferrell

**Comment by jwvirus** [comment]
newgif

**Comment by SeanOMealia** [comment]
the-mortified-punter11_thumb

**Comment by TomBradyWannabe** [comment]
Takei

**Comment by G-Thiara** [comment]
Thanks Peter. @certify is too slow

**Comment by AmmarHub** [comment]
:[](http://media.giphy.com/media/3o85xmYPgg7QFaJFEk/giphy.gif)

**Comment by BenKozy** [comment]
funny-gifs-pictures-2015-gif

**Comment by G-Thiara** [comment]
Hey @certify. About time you add me as a collaborator

**Comment by BenKozy** [comment]
@G-Thiara i noticed you close yours but i still found it :trollface: 

please look to your left and wave when you see this.

**Pull request merged**
